export const aiExperts = [ { id: 1, name: "Krishnamurthy", price: "₹16/min", img: "https://i.pravatar.cc/120?img=12" },
  { id: 2, name: "Love Guru", price: "₹21/min", img: "https://i.pravatar.cc/120?img=15" },
  { id: 3, name: "Astro Ananya", price: "₹11/min", img: "https://i.pravatar.cc/120?img=29" },
  { id: 4, name: "Arjun Pandit", price: "₹11/min", img: "https://i.pravatar.cc/120?img=32" },
  { id: 5, name: "Acharya Joshi", price: "₹21/min", img: "https://i.pravatar.cc/120?img=5" },
  { id: 6, name: "Astro Kavya", price: "₹19/min", img: "https://i.pravatar.cc/120?img=7" },
  { id: 7, name: "Guru Mahesh", price: "₹20/min", img: "https://i.pravatar.cc/120?img=8" },
  { id: 8, name: "Astro Preeti", price: "₹22/min", img: "https://i.pravatar.cc/120?img=9" },
/* your array here */];
export const doctors = [{ id: 1, name: "Cancer Specialist", price: "₹25/min", img: "https://i.pravatar.cc/120?img=56" },
  { id: 2, name: "Newborn Care", price: "₹22/min", img: "https://i.pravatar.cc/120?img=52" },
  { id: 3, name: "Health Checkup", price: "₹19/min", img: "https://i.pravatar.cc/120?img=30" },
  { id: 4, name: "Heart Specialist", price: "₹20/min", img: "https://i.pravatar.cc/120?img=18" },
  { id: 5, name: "Nutritionist", price: "₹20/min", img: "https://i.pravatar.cc/120?img=34" },
  { id: 6, name: "Eye Care", price: "₹18/min", img: "https://i.pravatar.cc/120?img=35" },
  { id: 7, name: "ENT Specialist", price: "₹21/min", img: "https://i.pravatar.cc/120?img=54" },
  { id: 8, name: "Skin Expert", price: "₹23/min", img: "https://i.pravatar.cc/120?img=46" },
/* your array here */];
export const counsellors = [ { id: 1, name: "Anjali", price: "₹15/min", img: "https://i.pravatar.cc/120?img=44" },
  { id: 2, name: "Suresh", price: "₹18/min", img: "https://i.pravatar.cc/120?img=31" },
  { id: 3, name: "Ritika", price: "₹20/min", img: "https://i.pravatar.cc/120?img=38" },
  { id: 4, name: "Vikas", price: "₹14/min", img: "https://i.pravatar.cc/120?img=49" },
  { id: 5, name: "Aditi", price: "₹16/min", img: "https://i.pravatar.cc/120?img=41" },
  { id: 6, name: "Sameer", price: "₹19/min", img: "https://i.pravatar.cc/120?img=45" },
  { id: 7, name: "Priya", price: "₹22/min", img: "https://i.pravatar.cc/120?img=47" },
  { id: 8, name: "Manish", price: "₹17/min", img: "https://i.pravatar.cc/120?img=55" },
/* your array here */];
export const tarotReaders = [ { id: 1, name: "Tarot Aarti", price: "₹13/min", img: "https://i.pravatar.cc/120?img=24" },
  { id: 2, name: "Mystic Rohan", price: "₹16/min", img: "https://i.pravatar.cc/120?img=19" },
  { id: 3, name: "Divine Priya", price: "₹17/min", img: "https://i.pravatar.cc/120?img=28" },
  { id: 4, name: "Fortune Meera", price: "₹14/min", img: "https://i.pravatar.cc/120?img=23" },
  { id: 5, name: "Zen Ritesh", price: "₹15/min", img: "https://i.pravatar.cc/120?img=37" },
  { id: 6, name: "Tarot Ishita", price: "₹19/min", img: "https://i.pravatar.cc/120?img=26" },
  { id: 7, name: "Karma Anil", price: "₹22/min", img: "https://i.pravatar.cc/120?img=39" },
  { id: 8, name: "Astro Divya", price: "₹18/min", img: "https://i.pravatar.cc/120?img=33" },
/* your array here */];
export const yogaExperts = [  { id: 1, name: "Rishabh", price: "₹18/min", img: "https://i.pravatar.cc/120?img=50" },
  { id: 2, name: "Neha", price: "₹15/min", img: "https://i.pravatar.cc/120?img=42" },
  { id: 3, name: "Yogi Dev", price: "₹20/min", img: "https://i.pravatar.cc/120?img=53" },
  { id: 4, name: "Rekha", price: "₹17/min", img: "https://i.pravatar.cc/120?img=40" },
  { id: 5, name: "Anand", price: "₹22/min", img: "https://i.pravatar.cc/120?img=46" },
  { id: 6, name: "Kavita", price: "₹21/min", img: "https://i.pravatar.cc/120?img=48" },
  { id: 7, name: "Yogesh", price: "₹23/min", img: "https://i.pravatar.cc/120?img=43" },
  { id: 8, name: "Preeti", price: "₹19/min", img: "https://i.pravatar.cc/120?img=20" },
/* your array here */];
export const lifeCoaches = [  { id: 1, name: "Coach Aryan", price: "₹25/min", img: "https://i.pravatar.cc/120?img=27" },
  { id: 2, name: "Sneha", price: "₹24/min", img: "https://i.pravatar.cc/120?img=17" },
  { id: 3, name: "Rahul", price: "₹23/min", img: "https://i.pravatar.cc/120?img=36" },
  { id: 4, name: "Ananya", price: "₹26/min", img: "https://i.pravatar.cc/120?img=16" },
  { id: 5, name: "Arjun", price: "₹25/min", img: "https://i.pravatar.cc/120?img=14" },
  { id: 6, name: "Vikram", price: "₹24/min", img: "https://i.pravatar.cc/120?img=11" },
  { id: 7, name: "Ritu", price: "₹27/min", img: "https://i.pravatar.cc/120?img=10" },
  { id: 8, name: "Deepa", price: "₹22/min", img: "https://i.pravatar.cc/120?img=13" },
/* your array here */];
export const exploreCategories = [{ id: 1, icon: "🔮", title: "Astrology" },
  { id: 2, icon: "💖", title: "Love & Relationships" },
  { id: 3, icon: "💼", title: "Career Guidance" },
  { id: 4, icon: "🧘‍♀️", title: "Wellness & Yoga" },
  { id: 5, icon: "🩺", title: "Health Advice" },
  { id: 6, icon: "💭", title: "Counselling" },
  { id: 7, icon: "🎯", title: "Life Coaching" },
  { id: 8, icon: "📿", title: "Spiritual Growth" },
/* your category array */];
export const testimonials = [ { id: 1, name: "Tripti Saini, Delhi", text: "I booked a call and it changed my perspective — clear, calm and so helpful.", img: "https://i.pravatar.cc/80?img=21" },
  { id: 2, name: "Tushar Sharma, UP", text: "The expert was logical and respectful. Felt lighter after the call!", img: "https://i.pravatar.cc/80?img=25" },
/* your testimonial array */];
